/**
 * 技能市场 - 内置技能目录
 *
 * 静态定义的技能列表，包含官方认证的渠道、模型提供商等
 *
 * @module skill-marketplace/builtin-catalog
 */

import type { SkillPackage } from "./types.js";

const OFFICIAL_AUTHOR = {
  name: "OpenClaw Team",
  email: "dev@openclaw.cn",
  url: "https://openclaw.cn",
  verified: true,
};

const NOW = "2025-01-01T00:00:00Z";

/**
 * 默认评分 (新技能)
 */
const DEFAULT_RATING = {
  average: 0,
  count: 0,
  distribution: [0, 0, 0, 0, 0] as [number, number, number, number, number],
};

/**
 * 内置技能目录
 */
export const BUILTIN_SKILLS: SkillPackage[] = [
  // ===========================================================================
  // 渠道集成
  // ===========================================================================
  {
    id: "@openclaw/wecom",
    name: "企业微信",
    version: "1.0.0",
    description: "企业微信渠道集成，支持应用消息、会话消息",
    longDescription: `
## 企业微信渠道

支持企业微信自建应用的消息收发。

### 功能特性
- 接收用户消息 (文本、图片、语音、视频、文件)
- 发送消息 (文本、图片、语音、视频、文件、图文、卡片)
- 消息加解密 (AES-256-CBC)
- 用户信息获取
- 多应用支持

### 配置要求
- 企业 ID (CorpId)
- 应用 ID (AgentId)
- 应用 Secret
- Token & EncodingAESKey (用于消息加解密)
    `.trim(),
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/channels/wecom",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "channel",
    tags: ["企业微信", "wecom", "wechat-work", "消息", "渠道"],
    capabilities: [{ type: "channel", id: "wecom" }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin" },
    icon: "💼",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
    featured: true,
  },
  {
    id: "@openclaw/dingtalk",
    name: "钉钉",
    version: "1.0.0",
    description: "钉钉渠道集成，支持企业内部应用、机器人",
    longDescription: `
## 钉钉渠道

支持钉钉企业内部应用和机器人的消息收发。

### 功能特性
- 接收用户消息
- 发送消息 (文本、Markdown、卡片)
- 消息加解密
- 用户信息获取
- Outgoing 机器人支持

### 配置要求
- AppKey & AppSecret
- Token & AES Key (用于消息加解密)
    `.trim(),
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/channels/dingtalk",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "channel",
    tags: ["钉钉", "dingtalk", "消息", "渠道", "机器人"],
    capabilities: [{ type: "channel", id: "dingtalk" }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin" },
    icon: "📌",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
    featured: true,
  },
  {
    id: "@openclaw/feishu",
    name: "飞书",
    version: "1.0.0",
    description: "飞书渠道集成，支持企业自建应用",
    longDescription: `
## 飞书渠道

支持飞书企业自建应用的消息收发。

### 功能特性
- 接收用户消息 (文本、图片、富文本)
- 发送消息 (文本、图片、卡片)
- 消息加解密
- 用户信息获取
- 事件订阅

### 配置要求
- App ID & App Secret
- Verification Token
- Encrypt Key (可选)
    `.trim(),
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/channels/feishu",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "channel",
    tags: ["飞书", "feishu", "lark", "消息", "渠道"],
    capabilities: [{ type: "channel", id: "feishu" }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin" },
    icon: "🐦",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
    featured: true,
  },

  // ===========================================================================
  // 模型提供商
  // ===========================================================================
  {
    id: "@openclaw/deepseek",
    name: "DeepSeek",
    version: "1.0.0",
    description: "DeepSeek 模型提供商，支持 DeepSeek-V3、DeepSeek-R1",
    longDescription: `
## DeepSeek 模型提供商

集成 DeepSeek 的大语言模型。

### 支持的模型
- deepseek-chat (DeepSeek-V3)
- deepseek-reasoner (DeepSeek-R1)

### 特性
- OpenAI 兼容 API
- 流式输出
- 函数调用
- 高性价比

### 配置要求
- API Key (从 platform.deepseek.com 获取)
    `.trim(),
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/providers/deepseek",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "provider",
    tags: ["deepseek", "llm", "ai", "模型", "国产"],
    capabilities: [{ type: "provider", id: "deepseek" }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin" },
    icon: "🔮",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
    featured: true,
  },
  {
    id: "@openclaw/zhipu",
    name: "智谱 AI",
    version: "1.0.0",
    description: "智谱 AI 模型提供商，支持 GLM-4 系列",
    longDescription: `
## 智谱 AI 模型提供商

集成智谱 AI 的 GLM 系列模型。

### 支持的模型
- glm-4-plus
- glm-4-air
- glm-4-airx
- glm-4-flash
- glm-4v (多模态)

### 特性
- OpenAI 兼容 API
- 流式输出
- 函数调用
- 多模态支持

### 配置要求
- API Key (从 open.bigmodel.cn 获取)
    `.trim(),
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/providers/zhipu",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "provider",
    tags: ["智谱", "zhipu", "glm", "llm", "ai", "模型", "国产"],
    capabilities: [{ type: "provider", id: "zhipu" }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin" },
    icon: "🧠",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
    featured: true,
  },
  {
    id: "@openclaw/qwen",
    name: "通义千问",
    version: "1.0.0",
    description: "阿里云通义千问模型提供商，支持 Qwen 系列",
    longDescription: `
## 通义千问模型提供商

集成阿里云通义千问系列模型。

### 支持的模型
- qwen-turbo
- qwen-plus
- qwen-max
- qwen-vl (多模态)

### 特性
- OpenAI 兼容 API
- 流式输出
- 函数调用
- 多模态支持

### 配置要求
- API Key (从 dashscope.aliyun.com 获取)
    `.trim(),
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/providers/qwen",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "provider",
    tags: ["通义", "千问", "qwen", "阿里云", "llm", "ai", "模型", "国产"],
    capabilities: [{ type: "provider", id: "qwen" }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin" },
    icon: "☁️",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
    featured: true,
  },
  {
    id: "@openclaw/wenxin",
    name: "文心一言",
    version: "1.0.0",
    description: "百度文心一言模型提供商，支持 ERNIE 系列",
    longDescription: `
## 文心一言模型提供商

集成百度文心一言系列模型。

### 支持的模型
- ernie-4.0
- ernie-3.5-turbo
- ernie-speed

### 特性
- 流式输出
- 函数调用

### 配置要求
- API Key & Secret Key (从 cloud.baidu.com 获取)
    `.trim(),
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/providers/wenxin",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "provider",
    tags: ["文心", "一言", "wenxin", "ernie", "百度", "llm", "ai", "模型", "国产"],
    capabilities: [{ type: "provider", id: "wenxin" }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin" },
    icon: "🐻",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },

  // ===========================================================================
  // 工具技能
  // ===========================================================================
  {
    id: "@openclaw/web-search",
    name: "网络搜索",
    version: "1.0.0",
    description: "网络搜索工具，支持百度、必应等搜索引擎",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/tools/web-search",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["搜索", "search", "百度", "必应", "bing"],
    capabilities: [{ type: "tool", names: ["web_search"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin" },
    icon: "🔍",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/weather",
    name: "天气查询",
    version: "1.0.0",
    description: "获取当前天气和预报，无需 API Key",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://wttr.in/:help",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["天气", "weather", "查询", "wttr.in"],
    capabilities: [{ type: "tool", names: ["get_weather"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/weather" },
    icon: "🌤️",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/1password",
    name: "1Password",
    version: "1.0.0",
    description: "1Password CLI 密码管理，读取/注入密钥",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://developer.1password.com/docs/cli/get-started/",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["密码", "password", "1password", "secret", "安全"],
    capabilities: [{ type: "tool", names: ["1password"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/1password" },
    icon: "🔐",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/apple-notes",
    name: "Apple 备忘录",
    version: "1.0.0",
    description: "通过 memo CLI 管理 macOS 备忘录",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://github.com/antoniorodr/memo",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["备忘录", "notes", "apple", "memo", "笔记"],
    capabilities: [{ type: "tool", names: ["apple_notes"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/apple-notes" },
    icon: "📝",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/apple-reminders",
    name: "Apple 提醒事项",
    version: "1.0.0",
    description: "通过 remindctl CLI 管理 macOS 提醒事项",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://github.com/steipete/remindctl",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["提醒", "reminders", "apple", "待办", "todo"],
    capabilities: [{ type: "tool", names: ["apple_reminders"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/apple-reminders" },
    icon: "⏰",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/bear-notes",
    name: "Bear 笔记",
    version: "1.0.0",
    description: "通过 grizzly CLI 管理 Bear 笔记",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://bear.app",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["笔记", "notes", "bear", "markdown"],
    capabilities: [{ type: "tool", names: ["bear_notes"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/bear-notes" },
    icon: "🐻",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/blogwatcher",
    name: "博客监控",
    version: "1.0.0",
    description: "监控博客和 RSS/Atom 订阅更新",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://github.com/Hyaxia/blogwatcher",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["rss", "atom", "博客", "订阅", "监控"],
    capabilities: [{ type: "tool", names: ["blogwatcher"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/blogwatcher" },
    icon: "📰",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/blucli",
    name: "BluOS",
    version: "1.0.0",
    description: "BluOS CLI 控制播放、分组、音量",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://blucli.sh",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["音乐", "music", "bluos", "音响"],
    capabilities: [{ type: "tool", names: ["bluos"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/blucli" },
    icon: "🫐",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/camsnap",
    name: "摄像头抓拍",
    version: "1.0.0",
    description: "从 RTSP/ONVIF 摄像头抓取画面或视频片段",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://camsnap.ai",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["摄像头", "camera", "rtsp", "监控"],
    capabilities: [{ type: "tool", names: ["camsnap"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/camsnap" },
    icon: "📸",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/canvas",
    name: "Canvas 画布",
    version: "1.0.0",
    description: "在 OpenClaw 客户端显示 HTML 内容",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/tools/canvas",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["canvas", "html", "显示", "渲染"],
    capabilities: [{ type: "tool", names: ["canvas"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/canvas" },
    icon: "🎨",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/clawdhub",
    name: "ClawdHub",
    version: "1.0.0",
    description: "技能市场 CLI，搜索、安装、发布技能",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://clawdhub.com",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["技能", "skill", "marketplace", "插件"],
    capabilities: [{ type: "tool", names: ["clawdhub"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/clawdhub" },
    icon: "🏪",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/coding-agent",
    name: "编程助手",
    version: "1.0.0",
    description: "运行 Codex CLI、Claude Code 等编程代理",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/tools/coding-agent",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["编程", "coding", "agent", "代码"],
    capabilities: [{ type: "tool", names: ["coding_agent"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/coding-agent" },
    icon: "🧩",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/eightctl",
    name: "Eight Sleep",
    version: "1.0.0",
    description: "Eight Sleep 智能床垫温度、闹钟控制",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://eightctl.sh",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["智能家居", "sleep", "床垫", "温度"],
    capabilities: [{ type: "tool", names: ["eight_sleep"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/eightctl" },
    icon: "🎛️",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/food-order",
    name: "外卖点餐",
    version: "1.0.0",
    description: "Foodora 复购订单、追踪配送状态",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://ordercli.sh",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["外卖", "food", "点餐", "配送"],
    capabilities: [{ type: "tool", names: ["food_order"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/food-order" },
    icon: "🥡",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/gifgrep",
    name: "GIF 搜索",
    version: "1.0.0",
    description: "搜索 GIF 并下载、提取静态帧",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://gifgrep.com",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["gif", "表情", "搜索", "图片"],
    capabilities: [{ type: "tool", names: ["gifgrep"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/gifgrep" },
    icon: "🧲",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/github",
    name: "GitHub",
    version: "1.0.0",
    description: "GitHub CLI 管理 Issue、PR、CI",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://cli.github.com",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["github", "git", "代码", "ci", "pr"],
    capabilities: [{ type: "tool", names: ["github"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/github" },
    icon: "🐙",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/himalaya",
    name: "邮件 (Himalaya)",
    version: "1.0.0",
    description: "IMAP/SMTP 邮件管理 CLI",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://github.com/pimalaya/himalaya",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["邮件", "email", "imap", "smtp"],
    capabilities: [{ type: "tool", names: ["email"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/himalaya" },
    icon: "📧",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/imsg",
    name: "iMessage",
    version: "1.0.0",
    description: "iMessage/SMS 消息列表、历史、发送",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://imsg.to",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["imessage", "sms", "消息", "apple"],
    capabilities: [{ type: "tool", names: ["imessage"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/imsg" },
    icon: "📨",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/local-places",
    name: "本地地点搜索",
    version: "1.0.0",
    description: "通过本地代理搜索附近餐厅、咖啡店等",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://github.com/Hyaxia/local_places",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["地点", "places", "搜索", "本地"],
    capabilities: [{ type: "tool", names: ["local_places"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/local-places" },
    icon: "📍",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/mcporter",
    name: "MCP Porter",
    version: "1.0.0",
    description: "MCP 服务器/工具的 CLI 调用和配置",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "http://mcporter.dev",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["mcp", "tool", "server", "集成"],
    capabilities: [{ type: "tool", names: ["mcp"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/mcporter" },
    icon: "📦",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/model-usage",
    name: "模型用量",
    version: "1.0.0",
    description: "CodexBar 模型使用量统计",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/tools/model-usage",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["统计", "usage", "cost", "模型"],
    capabilities: [{ type: "tool", names: ["model_usage"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/model-usage" },
    icon: "📊",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/nano-banana-pro",
    name: "Gemini 图片生成",
    version: "1.0.0",
    description: "通过 Gemini 3 Pro 生成或编辑图片",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://ai.google.dev/",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["图片", "image", "gemini", "生成", "ai"],
    capabilities: [{ type: "tool", names: ["image_gen"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/nano-banana-pro" },
    icon: "🍌",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/nano-pdf",
    name: "PDF 编辑",
    version: "1.0.0",
    description: "用自然语言指令编辑 PDF",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://pypi.org/project/nano-pdf/",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["pdf", "编辑", "文档"],
    capabilities: [{ type: "tool", names: ["pdf"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/nano-pdf" },
    icon: "📄",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/notion",
    name: "Notion",
    version: "1.0.0",
    description: "Notion API 创建和管理页面、数据库",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://developers.notion.com",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["notion", "笔记", "数据库", "协作"],
    capabilities: [{ type: "tool", names: ["notion"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/notion" },
    icon: "📝",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/obsidian",
    name: "Obsidian",
    version: "1.0.0",
    description: "Obsidian 知识库管理和自动化",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://help.obsidian.md",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["obsidian", "笔记", "markdown", "知识库"],
    capabilities: [{ type: "tool", names: ["obsidian"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/obsidian" },
    icon: "💎",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/openai-image-gen",
    name: "OpenAI 图片生成",
    version: "1.0.0",
    description: "OpenAI Images API 批量生成图片",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://platform.openai.com/docs/api-reference/images",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["图片", "image", "openai", "dalle", "生成"],
    capabilities: [{ type: "tool", names: ["openai_image"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/openai-image-gen" },
    icon: "🖼️",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/openai-whisper",
    name: "Whisper 本地语音转文字",
    version: "1.0.0",
    description: "本地 Whisper 语音转文字，无需 API Key",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openai.com/research/whisper",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["语音", "whisper", "转文字", "stt"],
    capabilities: [{ type: "tool", names: ["whisper"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/openai-whisper" },
    icon: "🎙️",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/openai-whisper-api",
    name: "Whisper API 语音转文字",
    version: "1.0.0",
    description: "OpenAI Whisper API 语音转文字",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://platform.openai.com/docs/guides/speech-to-text",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["语音", "whisper", "openai", "转文字", "api"],
    capabilities: [{ type: "tool", names: ["whisper_api"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/openai-whisper-api" },
    icon: "☁️",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/openhue",
    name: "Philips Hue",
    version: "1.0.0",
    description: "控制 Philips Hue 灯光和场景",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://www.openhue.io/cli",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["智能家居", "hue", "灯光", "philips"],
    capabilities: [{ type: "tool", names: ["hue"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/openhue" },
    icon: "💡",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/oracle",
    name: "Oracle CLI",
    version: "1.0.0",
    description: "Oracle CLI 提示词和文件打包",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://askoracle.dev",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["oracle", "prompt", "ai", "cli"],
    capabilities: [{ type: "tool", names: ["oracle"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/oracle" },
    icon: "🧿",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/peekaboo",
    name: "Peekaboo",
    version: "1.0.0",
    description: "macOS UI 截图和自动化",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://peekaboo.boo",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["截图", "ui", "自动化", "macos"],
    capabilities: [{ type: "tool", names: ["peekaboo"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/peekaboo" },
    icon: "👀",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/sag",
    name: "ElevenLabs TTS",
    version: "1.0.0",
    description: "ElevenLabs 文字转语音",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://sag.sh",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["语音", "tts", "elevenlabs", "合成"],
    capabilities: [{ type: "tool", names: ["tts"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/sag" },
    icon: "🗣️",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/session-logs",
    name: "会话日志",
    version: "1.0.0",
    description: "搜索和分析历史会话日志",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/tools/session-logs",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["日志", "logs", "会话", "搜索"],
    capabilities: [{ type: "tool", names: ["session_logs"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/session-logs" },
    icon: "📜",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/sherpa-onnx-tts",
    name: "本地 TTS",
    version: "1.0.0",
    description: "本地离线文字转语音 (sherpa-onnx)",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://github.com/k2-fsa/sherpa-onnx",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["语音", "tts", "本地", "离线"],
    capabilities: [{ type: "tool", names: ["local_tts"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/sherpa-onnx-tts" },
    icon: "🗣️",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/skill-creator",
    name: "技能创建器",
    version: "1.0.0",
    description: "创建和更新 AgentSkills",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/tools/skill-creator",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["技能", "skill", "创建", "开发"],
    capabilities: [{ type: "tool", names: ["skill_creator"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/skill-creator" },
    icon: "🛠️",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/songsee",
    name: "音频可视化",
    version: "1.0.0",
    description: "生成音频频谱图和特征面板",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://github.com/steipete/songsee",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["音频", "audio", "可视化", "频谱"],
    capabilities: [{ type: "tool", names: ["songsee"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/songsee" },
    icon: "🌊",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/sonoscli",
    name: "Sonos",
    version: "1.0.0",
    description: "Sonos 音箱发现、播放、音量、分组",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://sonoscli.sh",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["音乐", "music", "sonos", "音响"],
    capabilities: [{ type: "tool", names: ["sonos"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/sonoscli" },
    icon: "🔊",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/summarize",
    name: "摘要提取",
    version: "1.0.0",
    description: "从 URL、播客、本地文件提取摘要或文字",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://summarize.sh",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["摘要", "summarize", "转录", "文字"],
    capabilities: [{ type: "tool", names: ["summarize"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/summarize" },
    icon: "🧾",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/things-mac",
    name: "Things 3",
    version: "1.0.0",
    description: "macOS Things 3 任务管理",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://github.com/ossianhempel/things3-cli",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["任务", "todo", "things", "待办"],
    capabilities: [{ type: "tool", names: ["things"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/things-mac" },
    icon: "✅",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/tmux",
    name: "Tmux",
    version: "1.0.0",
    description: "远程控制 tmux 会话",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://github.com/tmux/tmux",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["tmux", "终端", "terminal", "会话"],
    capabilities: [{ type: "tool", names: ["tmux"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/tmux" },
    icon: "🧵",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/trello",
    name: "Trello",
    version: "1.0.0",
    description: "Trello 看板、列表、卡片管理",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://developer.atlassian.com/cloud/trello/rest/",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["trello", "看板", "任务", "协作"],
    capabilities: [{ type: "tool", names: ["trello"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/trello" },
    icon: "📋",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/video-frames",
    name: "视频帧提取",
    version: "1.0.0",
    description: "用 ffmpeg 从视频提取帧或片段",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://ffmpeg.org",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["视频", "video", "ffmpeg", "帧"],
    capabilities: [{ type: "tool", names: ["video_frames"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/video-frames" },
    icon: "🎞️",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
  {
    id: "@openclaw/voice-call",
    name: "语音通话",
    version: "1.0.0",
    description: "OpenClaw 语音通话插件",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/tools/voice-call",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "tool",
    tags: ["语音", "voice", "通话", "call"],
    capabilities: [{ type: "tool", names: ["voice_call"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin", skillPath: "skills/voice-call" },
    icon: "📞",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },

  // ===========================================================================
  // 安全合规
  // ===========================================================================
  {
    id: "@openclaw/content-filter",
    name: "内容过滤",
    version: "1.0.0",
    description: "内容安全过滤，敏感词检测与过滤",
    author: OFFICIAL_AUTHOR,
    license: "MIT",
    homepage: "https://openclaw.cn/docs/security/content-filter",
    repository: "https://github.com/openclaw-cn/openclaw-cn",
    category: "security",
    tags: ["安全", "过滤", "敏感词", "合规"],
    capabilities: [{ type: "hook", events: ["message_sending", "message_received"] }],
    engines: { openclaw: ">=0.1.0" },
    source: { type: "builtin" },
    icon: "🛡️",
    publishedAt: NOW,
    updatedAt: NOW,
    downloads: 0,
    rating: DEFAULT_RATING,
    verified: true,
  },
];

/**
 * 获取所有内置技能
 */
export function getBuiltinSkills(): SkillPackage[] {
  return BUILTIN_SKILLS;
}

/**
 * 根据 ID 获取内置技能
 */
export function getBuiltinSkillById(id: string): SkillPackage | undefined {
  return BUILTIN_SKILLS.find((skill) => skill.id === id);
}

/**
 * 获取推荐的内置技能
 */
export function getFeaturedSkills(): SkillPackage[] {
  return BUILTIN_SKILLS.filter((skill) => skill.featured);
}

/**
 * 按分类获取内置技能
 */
export function getBuiltinSkillsByCategory(category: string): SkillPackage[] {
  return BUILTIN_SKILLS.filter((skill) => skill.category === category);
}
